#!/usr/bin/python
import cgi
import random

first_words = ["Once upon a time,", "In a land far away,", "A long time ago,", "In the distant past,"]
middle_words = ["there lived a", "there was a", "there was an", "there existed a"]
descriptors = ["strong", "brave", "courageous", "fierce", "daring", "adventurous", "noble"]
nouns = ["knight", "princess", "dragon", "queen", "king", "prince", "unicorn"]
last_words = ["who ruled the kingdom with wisdom.", "who fought for justice.", "who lived happily ever after.", "and lived a long and prosperous life."]

def generate_text():
    first_word = random.choice(first_words)
    middle_word = random.choice(middle_words)
    descriptor = random.choice(descriptors)
    noun = random.choice(nouns)
    last_word = random.choice(last_words)
    text = f"{first_word} {middle_word} {descriptor} {noun} {last_word}"
    return text


print("<html>")
print("<head><title>Python CGI</title></head>")
print("<body>")
print("<h1>Randomly generated sentence:</h1>")
print(generate_text())
print("<h1>Manifeste de la guerilla - Aaron Swartz</h1>")
print("<p>L'information, c'est le pouvoir. Mais comme pour tout pouvoir, il y a ceux qui</p>")
print("<p>veulent le garder pour eux. Le patrimoine culturel et scientifique mondial, publie</p>")
print("<p>depuis plusieurs siecles dans les livres et les revues, est de plus en plus souvent</p>")
print("<p>numerise puis verrouille par une poignee d'entreprises privees. Vous voulez lire</p>")
print("<p>les articles presentant les plus celebres resultats scientifiques ? Il vous faudra</p>")
print("<p>payer de grosses sommes a des editeurs comme Reed Elsevier.</p>")
print("<p>Et il y a ceux qui luttent pour que cela change. Le mouvement pour le libre acces</p>")
print("<p>s'est vaillamment battu pour s'assurer que les scientifiques ne mettent pas toutes</p>")
print("<p>leurs publications sous copyright et s'assurer plutot que leurs travaux seront</p>")
print("<p>publies sur Internet sous des conditions qui en permettent l'acces a tous. Mais,</p>")
print("<p>meme dans le scenario le plus optimiste, la politique de libre acces ne concerne</p>")
print("<p>que les publications futures. Tout ce qui a ete fait jusqu'a present est perdu.</p>")
print("<p>C'est trop cher paye. Contraindre les universitaires a debourser de l'argent pour</p>")
print("<p>lire le travail de leurs collegues ? Numeriser des bibliotheques entieres mais ne</p>")
print("<p>permettre qu'aux gens de chez Google de les lire ? Fournir des articles</p>")
print("<p>scientifiques aux chercheurs des plus grandes universites des pays riches, mais</p>")
print("<p>pas aux enfants des pays du Sud ? C'est scandaleux et inacceptable.</p>")
print("<p>Nombreux sont ceux qui disent : \" Je suis d'accord mais que peut-on y faire ? Les</p>")
print("<p>entreprises possedent les droits de reproduction de ces documents, elles gagnent</p>")
print("<p>enormement d'argent en faisant payer l'acces, et c'est parfaitement legal, il n'y a</p>")
print("<p>rien que l'on puisse faire pour les en empecher. \" Mais si, on peut faire quelque</p>")
print("<p>chose, ce qu'on est deja en train de faire : riposter.</p>")
print("<p>Vous qui avez acces a ces ressources, etudiants, bibliothecaires, scientifiques, on</p>")
print("<p>vous a donne un privilege. Vous pouvez vous nourrir au banquet de la</p>")
print("<p>connaissance pendant que le reste du monde en est exclu. Mais vous n'etes pas</p>")
print("<p>obliges - moralement, vous n'en avez meme pas le droit - de conserver ce</p>")
print("<p>privilege pour vous seuls. Il est de votre devoir de le partager avec le monde. Et</p>")
print("<p>c'est ce que vous avez fait : en echangeant vos mots de passe avec vos collegues,</p>")
print("<p>en remplissant des formulaires de telechargement pour vos amis.</p>")
print("<p>Pendant ce temps, ceux qui ont ete ecartes de ce festin n'attendent pas sans rien</p>")
print("<p>faire. Vous vous etes faufiles dans les breches et avez escalade les barrieres,</p>")
print("<p>liberant l'information verrouillee par les editeurs pour la partager avec vos amis.</p>")
print("<p>Mais toutes ces actions se deroulent dans l'ombre, de facon souterraine. On les</p>")
print("<p>qualifie de \" vol \" ou bien de \" piratage \", comme si partager une abondance de</p>")
print("<p>connaissances etait moralement equivalent a l'abordage d'un vaisseau et au</p>")
print("<p>meurtre de son equipage. Mais le partage n'est pas immoral, c'est un imperatif</p>")
print("<p>moral. Seuls ceux qu'aveugle la cupidite refusent une copie a leurs amis.</p>")
print("<p>Les grandes multinationales, bien sur, sont aveuglees par la cupidite. Les lois qui</p>")
print("<p>les gouvernent l'exigent, leurs actionnaires se revolteraient a la moindre</p>")
print("<p>occasion. Et les politiciens qu'elles ont achetes les soutiennent en votant des lois</p>")
print("<p>qui leur donnent le pouvoir exclusif de decider qui est en droit de faire des copies.</p>")
print("<p>La justice ne consiste pas a se soumettre a des lois injustes. Il est temps de sortir</p>")
print("<p>de l'ombre et, dans la grande tradition de la desobeissance civile, d'affirmer notre</p>")
print("<p>opposition a la confiscation criminelle de la culture publique.</p>")
print("<p>Nous avons besoin de recolter l'information ou qu'elle soit stockee, d'en faire des</p>")
print("<p>copies et de la partager avec le monde. Nous devons nous emparer du domaine</p>")
print("<p>public et l'ajouter aux archives. Nous devons acheter des bases de donnees</p>")
print("<p>secretes et les mettre sur le Web. Nous devons telecharger des revues</p>")
print("<p>scientifiques et les poster sur des reseaux de partage de fichiers. Nous devons</p>")
print("<p>mener le combat de la guerilla pour le libre acces.</p>")
print("<p>Lorsque nous serons assez nombreux de par le monde, nous n'enverrons pas</p>")
print("<p>seulement un puissant message d'opposition a la privatisation de la</p>")
print("<p>connaissance : nous ferons en sorte que cette privatisation appartienne au passe.</p>")
print("<p>Serez-vous des notres ?</p>")
print()
print("<p>Aaron Swartz</p>")
print("</body>")
print("</html>")